import collections


seasons = {
2015: '''
Max McCaffrey
Michael Davis
Antonio Callaway
Myles Garrett
Maurkice Pouncey
Larry Ogunjobi
Robert Nkemdiche
Mark Walton
Alex Collins
Terry Beckner Jr.
Cordy Glenn
Michael Bennett
P.J. Williams
Isaiah Searight
Vontaze Burfict
Tyrel Dodson
Nathan Shepherd
Rod Taylor
De'Anthony Thomas
Lance Kendricks
Brandon Copeland
Antonio Callaway
Robert Quinn
Nevin Lawson
Morris Claiborne
Golden Tate
Taylor Lewan
Holton Hill
Jarran Reed
Rashard Robinson
Roc Thomas
Chris Herndon
Malik McDowell
Ryan Smith
Aaron Neary
David Onyemata
Jalin Marshall
Rico Gathers
Antonio Garcia
Leonte Carroo
Chad Kelly
Benjamin Watson
Alex Redmond
Patrick Peterson
Dion Jordan
Azeem Victor
Ra'Shede Hageman
Jhurrell Pressley
Holton Hill
Kareem Hunt
David Irving
Randy Gregory
''',

2018: '''
Nickell Robey-Coleman
Nickell Robey-Coleman
Denico Autry
Marcus Peters
Trey Flowers
Trenton Brown
J.J. Wilcox
Timmy Jernigan
Michael Bennett
Adrian Amos
Jadeveon Clowney
Samson Ebukam
Antwaun Woods
Antone Exum
Kiko Alonso
Tyreek Hill
Robert Quinn
Jordan Mills
Minkah Fitzpatrick
Pat O'Donnell
Marcus Davenport
Demarcus Robinson
Alex Redmond
George Odum
Ramon Foster
Deon Bush
Roquan Smith
Taylor Lewan
Josh Hill
Julian Edelman
Jadeveon Clowney
Randy Gregory
Leonard Williams
Baker Mayfield
Anthony Miller
Josh Bellamy
Richard Sherman
Marcell Harris
Telvin Smith
Josh Norman
Brian Hill
Trenton Cannon
Darryl Roberts
DeForest Buckner
Josh Jones
Eric Reid
Jadeveon Clowney
Jamie Collins
Antonio Callaway
Breshad Perriman
Andrus Peat
David Mayo
Jamar Taylor
Marcus Peters
Chandler Jones
Bobby Wagner
Justin Coleman
Jimmy Smith
Kenneth Dixon
Josh Mauro
Josh Gordon
Alex Light
Martavis Bryant
Ezekiel Elliott
Kamu Grugier-Hill
Malik Hooker
Deion Jones
Damontae Kazee
Corey Linsley
Matt Judon
Malcolm Jenkins
Jermaine Whitehead
Henry Anderson
Josh Bellamy
Antone Exum
Matthew Adams
Kiko Alonso
Bobby Wagner
Demario Davis
Taylor Lewan
Johnathan Hankins
Josh Doctson
Buster Skrine
Dion Dawkins
Marshon Lattimore
Vontaze Burfict
''',

2017: '''
Jerry Hughes
Chase Daniel
Ndamukong Suh
Ezekiel Ansah
Dante Fowler Jr.
Jatavis Brown
Vic Beasley
Taylor Lewan
Darron Lee
Jaylon Smith
Matthew Adams
Kyle Nelson
Daniel Ekuale
Cordarrelle Patterson
Shaq Lawson
Ezekiel Elliott
Xavier Woods
Kentrell Brice
Deatrich Wise
Takkarist McKinley
Glover Quin
Genard Avery
Travis Carrie
Micah Hyde
Sean Smith
Harrison Smith
Tyreek Hill
Calais Campbell
Alvin Kamara
Malcolm Jenkins
Bashaud Breeland
Yannick Ngakoue
Telvin Smith
Olivier Vernon
Justin Simmons
Eric Murray
Jeff Richards
Derwin James
George Odum
Dre Kirkpatrick
Quenton Nelson
Aaron Donald
Eric Reid
Davante Adams
Alec Ogletree
Nathan Stupar
Vernon Butler
Johnathan Hankins
Adrian Phillips
Ndamukong Suh
Dante Fowler Jr.
Justin Britt
David Onyemata
Michael Thomas
Aaron Lynch
Vernon Butler
Anthony Hitchens
Jermaine Whitehead
Eric Weddle
David Onyemata
Derwin James
Tyrann Mathieu
Andre Branch
Darius Philon
Rodger Saffold
Brandon Shell
Logan Thomas
Kevin Byard
Brandon Williams
Dede Westbrook
Kareem Hunt
Derek Wolfe
Haason Reddick
Josh Harvey-Clemons
Laquon Treadwell
Julian Edelman
Eric Reid
Jordan Whitehead
Eddie Jackson
Shawn Williams
Antwaun Woods
Darian Stewart
Emmanuel Sanders
LaMarcus Joyner
Vontaze Burfict
Bradley McDougald
Michael Bennett
Leonard Floyd
Quinton Jefferson
Matt Judon
Kemoko Turay
Alec Ogletree
Leonard Floyd
Damarious Randall
Emmanuel Ogbah
Terrance Williams
T.J. Watt
K'Waun Williams
Foyesade Oluokun
Tony Jefferson
Kevin King
Josh Jackson
Tony Brown
Najee Goode
Dee Ford
Chris Jones
Bruce Irvin
Martrell Spaight
Michael Thomas
Earl Thomas
Akiem Hicks
Xavier Rhodes
Kareem Hunt
Blake Martinez
Tashaun Gipson
Melvin Ingram
Darius Philon
Mychal Kendricks
Isaiah Crowell
Akeem Spence
Phillip Lindsay
Sean Davis
Darrius Heyward-Bey
Antone Exum
Damontae Kazee
Buster Skrine
Jadeveon Clowney
Andrew Sendejo
Torrey Smith
Takkarist McKinley
LeGarrette Blount
Nelson Agholor
Desmond King
Melvin Ingram
Antoine Bethea
Andre Branch
Shawn Williams
Duron Harmon
DeMarcus Lawrence
Yannick Ngakoue
Ereck Flowers
Marcus Peters
Aaron Donald
David Onyemata
Sheldon Richardson
Eric Saubert
Dylan Donahue
Matt Judon
Max McCaffrey
Nigel Bradham
Daryl Worley
Kentrell Brice
Yannick Ngakoue
Shamarko Thomas
Sterling Shepard
Fadol Brown
Antonio Hamilton
Antwione Williams
Jordan Jenkins
Darron Lee
Frankie Luvu
Jimmy Smith
Eli Rogers
Deiondre' Hall
Trevone Boykin
Jerrol Garcia-Williams
Carlos Henderson
Kevin Pierre-Louis
Rashard Robinson
ArDarius Stewart
Dante Fowler Jr.
Aaron Jones
Jamon Brown
Reuben Foster
Robert Turbin
Jameis Winston
Donald Stephenson
David Irving
Roy Miller
Julian Edelman
Victor Bolden
Demetrius Harris
Jerrell Freeman
Mark Ingram
Cayleb Jones
Vadal Alexander
Kentrell Brothers
Kent Taylor
Mark Sanchez
Jalen Collins
Thomas Davis
Josh Mauro
Corey Liuget
Josh Huff
Vontaze Burfict
Barry Church
Anthony Barr
Nigel Bradham
Terron Armstead
Trey Hendrickson
Telvin Smith
Wes Horton
Jairus Byrd
Jarvis Landry
Kenyan Drake
Leonard Johnson
Quandre Diggs
Darius Slay
Johnathan Joseph
T.Y. Hilton
Blake Countess
Alvin Kamara
Desmond Trufant
Geoff Swaim
Julie'n Davenport
Jadeveon Clowney
Yannick Ngakoue
Joey Bosa
Rayshawn Jenkins
Cassius Marsh
DeAndre Hopkins
Eli Apple
Khyri Thornton
Alex Boone
Ricardo Allen
Marshawn Lynch
Johnathan Joseph
Delano Hill
Robert Quinn
Nickell Robey-Coleman
Deon Lacey
David Bass
Sterling Shepard
Elvis Dumervil
Eric Reid
D.J. Swearinger
Charcandrick West
Thomas Davis
Vonn Bell
Chris Smith
Olivier Vernon
Germain Ifedi
Sheldon Richardson
Quinton Jefferson
Leonard Fournette
Matt Kalil
Benardrick McKinney
Garrett Celek
Trumaine Johnson
Korey Toomer
Sean Davis
David Parry
Shon Coleman
Marcus Peters
Darius Butler
Myles Jack
Daniel Sorensen
George Iloka
Marcus Peters
JuJu Smith-Schuster
Jimmy Smith
Rob Gronkowski
Jerry Hughes
Shane Ray
Richard Rodgers
Chandler Jones
Charles Johnson
Jabrill Peppers
Darian Stewart
Gabe Jackson
Blake Countess
Michael Bowie
Bryce Treggs
Michael Crabtree
Aqib Talib
T.J. Ward
Larry Fitzgerald
Earl Thomas
Kiko Alonso
Ryan Mallett
Daryl Worley
Tahir Whitehead
Kyle Long
Carson Wentz
Dean Lowry
Janoris Jenkins
Terrance Smith
P.J. Williams
Preston Smith
Johnny Holton
Marcus Gilbert
Marcus Gilbert
Karlos Dansby
Sheldon Richardson
Buster Skrine
Duke Johnson
Ben Koyack
Stefon Diggs
Darian Thompson
Kurt Coleman
Antoine Bethea
Haason Reddick
Frostee Rucker
Shaq Lawson
A.J. Green
Byron Jones
Xavier Woods
Jameis Winston
Mike Daniels
Jeremiah George
Rodger Saffold
Mario Edwards
Karl Joseph
Josh Norman
Carlos Hyde
A.J. Green
Mike Evans
Jeremy Kerley
Thomas Davis
Ahtyba Rubin
Darryl Roberts
Kiko Alonso
Matt Judon
Joe Thuney
Jamie Collins
Damien Wilson
Justin Simmons
Quandre Diggs
Sean Davis
D.J. Hayden
Cornelius Washington
Jeremiah Valoaga
Zach Cunningham
Bobby Wagner
Hayes Pullard
Shamar Stephen
Eric Wilson
Janoris Jenkins
Jerrell Freeman
Adrian Clayborn
Robert McClain
Akiem Hicks
Vontaze Burfict
Darron Lee
Darron Lee
Robby Anderson
Ndamukong Suh
Marcus Peters
Jon Bostic
Kentrell Brice
David Onyemata
Mark Glowinski
Antonio Morrison
Russell Okung
Zaire Anderson
Keenan Robinson
K.J. Wright
Niles Paul
Andrew Sendejo
Marshawn Lynch
Mike Mitchell
Mike Mitchell
Bud Dupree
Le'Veon Bell
De'Vondre Campbell
Grady Jarrett
Anthony Barr
Laquon Treadwell
Jake Ryan
Jaleel Johnson
Brandon Graham
Cameron Jordan
Josh Hill
Ron Leary
Pierre Garcon
D.J. Swearinger
Ezekiel Elliott
Luke Kuechly
Damarious Randall
Davante Adams
Marcus Gilchrist
Matt Kalil
Anthony Hitchens
Matt Elam
Dominique Rodgers-Cromartie
B.J. Daniels
Makinton Dorleant
Darius Latham
HaHa Clinton-Dix
Antonio Brown
Marquette King
Za'Darius Smith
Bashaud Breeland
Paul Posluszny
Danny Trevathan
Odell Beckham, Jr.
Will Parks
Crevon LeBlanc
Tarik Cohen
Marwin Evans
DeMarcus Lawrence
Tyrone Crawford
James Burgess
Daniel Sorensen
Jamal Adams
Darron Lee
Xavier Rhodes
Andrew Sendejo
Anthony Barr
LeGarrette Blount
Jimmie Ward
Ray-Ray Armstrong
Richard Sherman
Jack Conklin
Christian Kirksey
Christopher Conte
Tanner Gentry
Braxton Miller
Evan Engram
Timmy Jernigan
Harvey Langi
Bud Dupree
Buster Skrine
Cliff Avril
Ra'Shede Hageman
Lawrence Timmons
Marshawn Lynch
Kenny Vaccaro
Alex Anzalone
Darron Lee
Jaquiski Tartt
Ryan Shazier
William Gay
J.J. Wilcox
Melvin Ingram
Jarrad Davis
Martellus Bennett
Yannick Ngakoue
Travis Kelce
Daniel Sorensen
Linval Joseph
Stefon Diggs
Joe Walker
Brian Cushing
Josh Brown
Sam Shields
Willie Snead
Vontaze Burfict
Owamagbe Odighizuwa
Max Tuerk
Jaelen Strong
Bryce Treggs
Max Bullough
Jalen Collins
Damontre Moore
Duane Brown
Adam-Pacman Jones
Geronimo Allison
Armonty Bryant
Mike Thomas
Michael Floyd
Darren Waller
Khyri Thornton
Walter Powell
James Ihedigbo
Justin Gilbert
David Irving
Max Bullough
Troy Hill
Shaquelle Evans
Brandon Bostick
Nick Marshall
T.J. McDonald
Austin Seferian-Jenkins
Kenneth Dixon
Jalin Marshall
Letroy Guion
Trent Murphy
''',

2016: '''
J'Marcus Webb
Travis Kelce
Travis Kelce
Jadeveon Clowney
Eric Rowe
Bud Dupree
Jarvis Landry
Courtney Upshaw
LeGarrette Blount
Davante Adams
Randy Gregory
Chris Jones
Demetrius Harris
Jeremy Lane
Jermaine Gresham
Brandon Shell
Denzel Perryman
Damion Square
Anthony Brown
Sheldon Day
Stefon Diggs
Doug Martin
Markus Golden
Zach Orr
Bennie Logan
Danny Shelton
Aaron Donald
Aaron Donald
Michael Bennett
Cassius Marsh
Darius Butler
Thomas Davis
T.J. Lang
Stephon Tuitt
Marcus Gilbert
Damon Harrison
T.J. Ward
Jameis Winston
Jordan Reed
Isa Abdul-Quddus
Odell Beckham, Jr.
Ra'Shede Hageman
LaRoy Reynolds
Jihad Ward
Carlos Dunlap
Tyler Eifert
Emmanuel Sanders
Cornelius Washington
Richard Sherman
K.J. Wright
T.J. Green
Erik Walden
Chris Clark
Deshazor Everett
Deshazor Everett
Olivier Vernon
Olivier Vernon
Alvin Bailey
Tenny Palepoi
Jordan Payton
Dorial Green-Beckham
Nigel Bradham
Buster Skrine
Sheldon Richardson
Breno Giacomini
Todd Gurley
Trumaine Johnson
Odell Beckham, Jr.
Marquette King
Eric Pinkins
Joe Webb
Ramon Foster
Mike Pennel
D'Qwell Jackson
Rolando McClain
Eric Berry
Kareem Jackson
Derek Anderson
Corey Coleman
Julius Peppers
Antonio Brown
Le'Veon Bell
Sammie Lee Hill
Seantrel Henderson
Tom Johnson
Vontaze Burfict
Doug Baldwin
Vonn Bell
Kenny Vaccaro
Olivier Vernon
Daniel McCullers
Su'a Cravens
Johnathan Joseph
Rod Streater
Karlos Williams
Jude Adjei-Barimah
Jason Jones
Jerrell Freeman
Alan Branch
Rolando McClain
Keanu Neal
Kayvon Webster
Emmanuel Ogbah
Thomas Davis
Ted Larsen
Pernell McPhee
Ross Cockrell
Jarvis Jones
Kenny Vaccaro
Letroy Guion
Mike Daniels
Perrish Cox
Tajae Sharpe
Dante Fowler Jr.
Marcus Peters
Alshon Jeffery
Cameron Erving
Travis Kelce
Richard Sherman
David Irving
Ty Montgomery
Johnson Bademosi
Andre Branch
Quinton Patton
Buster Skrine
Sheldon Richardson
D.J. Fluker
Christine Michael
Taylor Lewan
Kenny Vaccaro
Calais Campbell
Rodney Gunter
Datone Jones
Leonard Johnson
Nickell Robey-Coleman
Shawn Williams
Shawn Williams
Dre Kirkpatrick
Marquis Flowers
Anthony Hitchens
Tavon Wilson
Jalen Ramsey
Dante Fowler Jr.
Karl Joseph
Donald Penn
Michael Crabtree
Josh Norman
Trent Williams
Armonty Bryant
Jarvis Landry
Cameron Clear
J.J. Worton
Byron Maxwell
Za'Darius Smith
Owamagbe Odighizuwa
Alex Boone
DeForest Buckner
Clay Matthews
Frostee Rucker
Rodney McLeod
Jalen Ramsey
Johnny Holton
Nick Fairley
Andre Branch
Chase Reynolds
Stephen Hill
Anquan Boldin
Kawann Short
LeGarrette Blount
Rob Gronkowski
Dre Kirkpatrick
Julian Edelman
Daimion Stafford
Justin Durant
Glover Quin
Aaron Donald
Vernon Davis
Fletcher Cox
Malik Jackson
Odell Beckham, Jr.
Janoris Jenkins
Vontaze Burfict
Derrick Coleman
Carlos Hyde
Adolphus Washington
Corbin Bryant
Fletcher Cox
Jadeveon Clowney
Ben Jones
Jason Jones
DeSean Jackson
Antonio Brown
Robert Blanton
Nickell Robey-Coleman
Aaron Williams
Terrelle Pryor
Brice Butler
Todd Davis
Curt Maggitt
Blake Bortles
Calvin Pryor
Michael Crabtree
Odell Beckham, Jr.
Ifeanyi Momah
Cam Newton
Mike Wallace
Spencer Ware
Jerick McKinnon
Brian Winters
Cassius Marsh
Josh Norman
Josh Norman
Steve Smith
Willie Young
Will Parks
Nick Perry
Jaelen Strong
Lawrence Timmons
Eli Harold
Allen Robinson
Weston Richburg
Odell Beckham, Jr.
Marquette King
Eric Decker
Sheldon Richardson
Stephon Gilmore
Mike Daniels
Devin Funchess
Kelvin Benjamin
Akiem Hicks
Javon Hargrave
Darian Stewart
Stefon Diggs
Randy Gregory
Manny Lawson
Antonio Brown
Aaron Donald
Aaron Donald
Antonio Brown
DeAndre Levy
Jerry Hughes
Cameron Fleming
Gerald McCoy
Chandler Jones
Julian Edelman
Robert Alford
Eric Decker
Michael Johnson
Odell Beckham, Jr.
Victor Cruz
Randall Cobb
DeAndre Hopkins
Michael Bennett
Jahleel Addae
Everson Griffen
Nikita Whitlock
Brandon Marshall
Darian Stewart
Trai Turner
Randy Gregory
Corey Moore
Tom Savage
Seantrel Henderson
Chris Scott
Rob Ninkovich
Bradley Roby
Laken Tomlinson
Crezdon Butler
Timmy Jernigan
Sammie Lee Hill
Prince Shembo
Jeremy Maclin
LaMarcus Joyner
Kerry Hyder
Damion Square
John Simon
Jarran Reed
Josh Brown
Zach Sterup
Marcell Dareus
Andrew Quarless
Shiloh Keo
Lane Johnson
Marqueston Huff
Adrian Peterson
Arthur Jones
Josh Gordon
Karlos Williams
Aaron Lynch
Sheldon Richardson
Rolando McClain
Darren Waller
Jace Davis
Bernard Pierce
Tom Brady
DeMarcus Lawrence
Silas Redd
Le'Veon Bell
Jalen Collins
Andrew Turzilli
Demetri Goodson
Aaron Colvin
Vontaze Burfict
Nick Boyle
Will Hill
Taylor Mays
Nick Moody
Martavis Bryant
Armonty Bryant
''',

2015: '''
Mike Pennel
Aqib Talib
Danny Amendola
Dezman Moses
Larry Fitzgerald
Adam-Pacman Jones
Ramon Foster
Domata Peko
Wallace Gilberry
Vontaze Burfict
Marcel Reece
Eric Weddle
Josh Norman
Josh Norman
Cody Wallace
Odell Beckham, Jr.
Brandon Boykin
William Gay
Vontaze Burfict
Mike Mitchell
David DeCastro
Ahmad Brooks
Andre Branch
A.J. Green
Jalen Saunders
Philip Wheeler
DeAndre Hopkins
Brandon Browner
Josh Bellamy
Chris Boswell
Phillip Supernaw
Justin Pugh
Antonio Brown
Nick Boyle
Kwon Alexander
Quinton Dial
Jaye Howard
Shawn Williams
Von Miller
DeAngelo Hall
Deone Bucannon
C.J. Mosley
Jahleel Addae
Chris Culliver
Frank Alexander
LaRon Landry
Stephen Hill
Wes Horton
Chris Johnson
T.J. Ward
Jah Reid
C.J. Mosley
Carson Palmer
K.J. Wright
Kendrick Lewis
Cam Newton
Willie Young
Arthur Moats
Silas Redd
Aldon Smith
Junior Galette
Michael Mauti
Jordan Matthews
Roman Harper
Josh Norman
T.J. Ward
T.J. Ward
Captain Munnerlyn
LaMarcus Joyner
David Bass
Ego Ferguson
Joseph Randle
Tayo Fabuluje
Jalen Saunders
Aqib Talib
Stedman Bailey
George Iloka
Johnathan Hankins
Brandon Browner
Ray-Ray Armstrong
Trey Watts
Kaleb Ramsey
Matt Elam
Nick Fairley
Andre Branch
Darrin Walls
Corey Liuget
Donald Penn
DeAngelo Williams
William Gay
Steven Nelson
Damontre Moore
Kroy Biermann
Kam Chancellor
D.J. Fluker
John Cyprien
Charcandrick West
Kevin Johnson
Quincy Enunwa
Sio Moore
Carlos Hyde
Michael Bennett
Mike Mitchell
A.J. Green
Clay Matthews
Cameron Heyward
Travis Coons
Malik Jackson
Stephon Tuitt
Jarvis Landry
Jerry Hughes
Jerry Hughes
Xavier Rhodes
Josh Norman
Stedman Bailey
J.R. Sweezy
Eddie Pleasant
Akeem Dent
Odell Beckham, Jr.
Martellus Bennett
John Simon
Von Miller
Sylvester Williams
Demario Davis
Peyton Thompson
Thomas Davis
K.J. Wright
T.J. Lang
Michael Bennett
DeMarcus Ware
Rashad Johnson
Malik Jackson
Harry Douglas
Joel Bitonio
Carlos Dunlap
Austin Howard
Jeremy Mincey
Isaiah Crowell
Adam-Pacman Jones
William Moore
Chris Culliver
IK Enemkpali
Brandon Spikes
Rodney Austin
Jermaine Cunningham
Jonathan Dwyer
Mike Williams
Kam Chancellor
Zeke Motta
T.J. Ward
Michael Bennett
R.J. Dill
Martavis Bryant
Jay Ratliff
Oday Aboushi
Jerome Simpson
Akeem Spence
Ryan Seymour
Da'Rick Rogers
Bobby Massie
Ace Sanders
Orson Charles
Bashaud Breeland
Derek Wolfe
Jabari Price
Sean Smith
Letroy Guion
Sheldon Richardson
Rolando McClain
Datone Jones
Antonio Gates
Trey Watts
Marcell Dareus
Dion Jordan
Josh Gordon
Greg Hardy
Eben Britton
Victor Butler
LeGarrette Blount
LaRon Landry

'''}

players = collections.defaultdict(lambda: set())

for year, season in seasons.items():
	season = season.strip()
	season = season.lower()
	season = season.replace(' & ', '\n')
	
	

	season = season.splitlines()
	seasons[year] = set(season)

	for player in season:
		players[player].add(year)

def years_played(season):
	return len(players[player])

for player in sorted(players, key=years_played, reverse=True):
	years = sorted(players[player])
	num_years = len(years)
	years = ', '.join(map(str, years))

	print ('%-15s (%s) %s' % (player, num_years, years))
